version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: botcraft-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bot_platform
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: